# Generated by Django 4.0.2 on 2022-02-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babarkotapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='user_details',
            name='std',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
