# Generated by Django 4.0.2 on 2022-04-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babarkotapp', '0002_bill_book_cash_book_cheque_register_gal_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gal_category',
            name='css_term',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
