# Generated by Django 4.0.2 on 2022-02-25 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babarkotapp', '0002_user_details_profile_picture_user_details_std'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='uside_code',
            new_name='udise_code',
        ),
    ]
