# Generated by Django 4.0.2 on 2022-04-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babarkotapp', '0003_gal_category_css_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gal_category',
            name='css_term',
        ),
        migrations.AddField(
            model_name='gallery',
            name='css_term',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
