# Generated by Django 4.0.2 on 2022-03-02 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babarkotapp', '0003_rename_uside_code_user_details_udise_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='category',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='poority_line',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='std',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='udise_code',
        ),
    ]
