# Generated by Django 4.0.2 on 2022-03-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babarkotapp', '0004_remove_user_details_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='General_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gr_number', models.IntegerField()),
                ('student_name', models.CharField(max_length=255)),
                ('religion', models.CharField(max_length=100)),
                ('birth_place', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('dob_in_words', models.CharField(max_length=50)),
                ('previous_school_std', models.TextField()),
                ('school_joining', models.DateField()),
                ('admission_std', models.CharField(max_length=50)),
                ('fees', models.CharField(max_length=50, null=True)),
                ('date_leaving', models.DateField()),
                ('leaving_std', models.CharField(max_length=50)),
                ('leaving_reason', models.TextField()),
                ('progress', models.CharField(max_length=50)),
                ('behaviour', models.CharField(max_length=50)),
                ('date_taking_lc', models.DateField()),
                ('note', models.TextField()),
            ],
        ),
    ]
