# Generated by Django 4.0.2 on 2022-03-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babarkotapp', '0006_general_register_guj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword_Defination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('english', models.CharField(max_length=255)),
                ('gujarati', models.CharField(max_length=255)),
            ],
        ),
    ]
