# Generated by Django 4.0.2 on 2022-03-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babarkotapp', '0007_keyword_defination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword_defination',
            name='english',
        ),
        migrations.RemoveField(
            model_name='keyword_defination',
            name='gujarati',
        ),
        migrations.AddField(
            model_name='keyword_defination',
            name='lang',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyword_defination',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
