# Generated by Django 4.0.2 on 2022-03-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babarkotapp', '0008_remove_keyword_defination_english_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='General_Register_guj',
        ),
        migrations.AddField(
            model_name='general_register',
            name='lang',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
