# Generated by Django 4.0.2 on 2022-03-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babarkotapp', '0009_delete_general_register_guj_general_register_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_register',
            name='date_leaving',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='general_register',
            name='date_taking_lc',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='general_register',
            name='dob',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='general_register',
            name='school_joining',
            field=models.CharField(max_length=50),
        ),
    ]
