# Generated by Django 4.0.2 on 2022-03-15 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babarkotapp', '0010_alter_general_register_date_leaving_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='Role',
        ),
    ]
