# Generated by Django 4.0.2 on 2022-03-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babarkotapp', '0011_remove_user_details_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.IntegerField()),
                ('grant_details', models.TextField()),
                ('amount', models.BigIntegerField()),
                ('order_no', models.CharField(max_length=100)),
                ('bank_deposite_date', models.DateField()),
                ('remarks', models.TextField()),
            ],
        ),
    ]
