# Generated by Django 4.0.2 on 2022-03-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babarkotapp', '0012_grant_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant_register',
            name='entry_no',
            field=models.IntegerField(unique=True),
        ),
    ]
