# Generated by Django 4.0.2 on 2022-03-21 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babarkotapp', '0013_alter_grant_register_entry_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.IntegerField()),
                ('date', models.DateField()),
                ('name_and_particulars', models.TextField()),
                ('voucher_no', models.BigIntegerField(blank=True, null=True)),
                ('total_amount', models.BigIntegerField()),
                ('debit_or_credit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='General_Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.IntegerField()),
                ('date', models.DateField()),
                ('particuars', models.TextField()),
                ('credit', models.CharField(max_length=50)),
                ('debit', models.CharField(max_length=50)),
                ('credit_bal', models.CharField(max_length=50)),
                ('debit_bal', models.CharField(max_length=50, null=True)),
                ('name_of_account', models.CharField(max_length=50)),
                ('c_b_r_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babarkotapp.cash_book')),
            ],
        ),
    ]
