# Generated by Django 4.0.2 on 2022-03-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babarkotapp', '0014_cash_book_general_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash_book',
            name='reciept',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
