# Generated by Django 4.0.2 on 2022-03-22 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babarkotapp', '0015_cash_book_reciept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general_ledger',
            old_name='particuars',
            new_name='particulars',
        ),
    ]
