# Generated by Django 4.0.2 on 2022-03-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babarkotapp', '0016_rename_particuars_general_ledger_particulars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash_book',
            name='reciept',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cash_book',
            name='total_amount',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cash_book',
            name='voucher_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='grant_register',
            name='amount',
            field=models.CharField(max_length=50),
        ),
    ]
