# Generated by Django 4.0.2 on 2022-03-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babarkotapp', '0017_alter_cash_book_reciept_alter_cash_book_total_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.IntegerField(unique=True)),
                ('date', models.DateField()),
                ('agency_name', models.CharField(max_length=255)),
                ('purchase_detail', models.CharField(max_length=255)),
                ('bill_no', models.CharField(max_length=50)),
                ('cheque_no', models.CharField(max_length=100)),
                ('cheque_date', models.DateField()),
                ('amount', models.CharField(max_length=50)),
                ('paying_amount', models.CharField(max_length=50)),
            ],
        ),
    ]
