# Generated by Django 4.0.2 on 2022-03-31 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babarkotapp', '0020_student_data_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
