# Generated by Django 4.0.2 on 2022-04-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babarkotapp', '0023_qoute'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_data',
            name='division',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_data',
            name='udise',
            field=models.CharField(default=0, max_length=155),
            preserve_default=False,
        ),
    ]
