# Generated by Django 4.0.2 on 2022-04-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babarkotapp', '0024_student_data_division_student_data_udise'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='qoute',
            new_name='Quote',
        ),
    ]
