# Generated by Django 4.0.2 on 2022-04-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babarkotapp', '0025_rename_qoute_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Useful_Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
