# Generated by Django 4.0.2 on 2022-04-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babarkotapp', '0027_noticeboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
                ('desc', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
