# Generated by Django 4.0.2 on 2022-04-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babarkotapp', '0028_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gal_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='category',
        ),
    ]
