# Generated by Django 4.0.2 on 2022-04-16 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babarkotapp', '0029_gal_category_remove_gallery_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='babarkotapp.gal_category'),
            preserve_default=False,
        ),
    ]
