# Generated by Django 4.0.2 on 2022-04-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babarkotapp', '0030_gallery_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_register',
            name='mother_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
